name: Integration Test

on:
  pull_request:
    branches:
      - master

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 22
        uses: actions/setup-java@v2
        with:
          java-version: '22'

      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}}
          restore-keys: ${{ runner.os }}-maven

      - name: Run Maven tests
        run: mvn clean test

      - name: Build the app
        run: mvn package -DskipTests

      - name: Check for successful Build
        run: echo "Integration test passed"


