
name: publish

on:
  push:
    branches:
      - master
jobs:
  dockerize:
    runs-on: ubuntu-latest

    env:
      BASE_URL: ${{ secrets.BASE_URL }}
      MONGO_DB: ${{ secrets.MONGO_DB }}
      JWT_SECRETS: ${{ secrets.JWT_SECRETS }}
      MONGO_URI: ${{ secrets.MONGO_URI }}
      GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/notes-management-system .

      - name: Login to dockerhub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/notes-management-system


        

